#!/usr/bin/env bash
# Verifies a staged release directory is exactly the reviewed eight-asset set and that every file
# matches the checksum manifest shipped beside it. Run by the rehearsal job as well as by publish,
# so a dispatched dry run proves the same asset boundary a tag push would.
#
# Usage: verify-release-assets.sh <directory> <version>
set -euo pipefail

directory="${1:?release asset directory is required}"
version="${2:?release version is required}"

expected=(
  "Zinc-${version}-Setup.exe"
  "Zinc-${version}-Setup.exe.blockmap"
  "latest.yml"
  "LICENSE"
  "THIRD_PARTY_NOTICES-${version}.md"
  "ASSET_PROVENANCE.md"
  "zinc-${version}.cdx.json"
  "SHA256SUMS.txt"
)

mapfile -t actual < <(find "$directory" -maxdepth 1 -type f -printf '%f\n' | sort)
mapfile -t wanted < <(printf '%s\n' "${expected[@]}" | sort)
if [[ "${actual[*]}" != "${wanted[*]}" ]]; then
  printf 'Expected release assets:\n%s\n' "${wanted[*]}" >&2
  printf 'Actual release assets:\n%s\n' "${actual[*]}" >&2
  exit 1
fi

# The manifest is written by Windows PowerShell, so strip CR before anything reads the filenames.
manifest="$(sed 's/\r$//' "$directory/SHA256SUMS.txt")"

# `sha256sum --check` only verifies the lines a manifest actually contains, so a truncated manifest
# would sail through with an "everything matched" exit code. Prove coverage first: the manifest must
# name exactly the seven non-manifest assets, once each, with no path component.
# Accept both separators sha256sum itself accepts: "  " (text mode, what the Windows job writes)
# and " *" (binary mode), so a manifest regenerated by a different tool cannot slip past unparsed.
mapfile -t manifest_names < <(printf '%s\n' "$manifest" | sed -n 's/^[a-fA-F0-9]\{64\} [ *]\(.*\)$/\1/p' | sort)
mapfile -t signed_assets < <(printf '%s\n' "${expected[@]}" | grep -vx 'SHA256SUMS.txt' | sort)

if [[ "${manifest_names[*]}" != "${signed_assets[*]}" ]]; then
  printf 'SHA256SUMS.txt must cover exactly these assets:\n%s\n' "${signed_assets[*]}" >&2
  printf 'It actually covers:\n%s\n' "${manifest_names[*]}" >&2
  exit 1
fi

(
  cd "$directory"
  printf '%s\n' "$manifest" | sha256sum --check --strict -
)

printf 'Release assets verified: %s files present, %s covered by the checksum manifest.\n' \
  "${#expected[@]}" "${#signed_assets[@]}"
